"""Initial Migration

Revision ID: fce7fac79f63
Revises: 
Create Date: 2024-03-19 11:19:32.695833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce7fac79f63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('age', sa.String(length=30), nullable=True),
    sa.Column('street_name', sa.String(length=100), nullable=True),
    sa.Column('street_number', sa.String(length=20), nullable=True),
    sa.Column('postcode', sa.String(length=30), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('employee_picture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picture_size', sa.String(length=100), nullable=True),
    sa.Column('picture', sa.String(length=100), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_picture')
    op.drop_table('employee')
    # ### end Alembic commands ###
